spring:
  application:
    name: server
  data:
    redis:
      host: localhost
      port: 6379
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

aws:
  accessKey: *
  secretKey: *
  region: ap-northeast-2